import type { LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

export function Page({ children, className }: { children: ReactNode; className?: string }) { return <main className={cn("mx-auto min-h-[calc(100vh-4rem)] max-w-7xl px-4 py-10 sm:px-6 lg:py-14", className)}>{children}</main>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div>{eyebrow && <div className="mb-3 text-xs font-bold uppercase text-primary">{eyebrow}</div>}<h1 className="text-balance text-3xl font-bold sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{description}</p></div>{action}</div>; }
export function Panel({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("glass-panel rounded-lg p-5", className)}>{children}</div>; }
export function Badge({ children, tone = "default" }: { children: ReactNode; tone?: "default" | "success" | "warning" }) { return <span className={cn("inline-flex items-center rounded-md border px-2 py-1 text-xs font-semibold", tone === "success" ? "border-success/30 bg-success/10 text-success" : tone === "warning" ? "border-warning/30 bg-warning/10 text-warning" : "border-primary/25 bg-primary/10 text-primary")}>{children}</span>; }
export function Stat({ icon: Icon, label, value, note }: { icon: LucideIcon; label: string; value: string; note: string }) { return <Panel><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></div><span className="grid size-10 place-items-center rounded-md bg-primary/10 text-primary"><Icon /></span></div></Panel>; }
export function Progress({ value }: { value: number }) { return <div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${value}%` }} /></div>; }
export const fieldClass = "w-full rounded-md border border-input bg-background/60 px-3 py-2.5 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20";